insert into "genres" ("id", "name") values (46, 'Family');
insert into "genres" ("id", "name") values (50, 'History');
insert into "genres" ("id", "name") values (1, 'Animation');
insert into "genres" ("id", "name") values (17, 'Comedy');
insert into "genres" ("id", "name") values (9, 'Mystery');
insert into "genres" ("id", "name") values (3, 'Fantasy');
insert into "genres" ("id", "name") values (34, 'Drama');
insert into "genres" ("id", "name") values (235, 'Western');
insert into "genres" ("id", "name") values (73, 'Romance');
insert into "genres" ("id", "name") values (2, 'Action');
insert into "genres" ("id", "name") values (13, 'Adventure');
insert into "genres" ("id", "name") values (4, 'Thriller');
insert into "genres" ("id", "name") values (44, 'Music');
insert into "genres" ("id", "name") values (7, 'Horror');
insert into "genres" ("id", "name") values (5, 'Science Fiction');
insert into "genres" ("id", "name") values (53, 'War');
insert into "genres" ("id", "name") values (231, 'Documentary');
insert into "genres" ("id", "name") values (267, 'TV Movie');
insert into "genres" ("id", "name") values (16, 'Crime');
