CREATE TABLE
  public.locations (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL
  );

ALTER TABLE
  public.locations
ADD
  CONSTRAINT locations_pkey PRIMARY KEY (id)