CREATE TABLE
  public.schedules (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    movies_id integer NOT NULL,
    cinemas_id integer NOT NULL,
    times_id integer NOT NULL,
    locations_id integer NOT NULL,
    date date NOT NULL
  );

ALTER TABLE
  public.schedules
ADD
  CONSTRAINT schedules_pkey PRIMARY KEY (id)