CREATE TABLE
  public.movies_casts (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    movies_id integer NULL,
    casts_id integer NULL
  );

ALTER TABLE
  public.movies_casts
ADD
  CONSTRAINT movie_casts_pkey PRIMARY KEY (id)