CREATE TABLE
  public.movies_genres (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    movies_id integer NULL,
    genres_id integer NULL
  );

ALTER TABLE
  public.movies_genres
ADD
  CONSTRAINT movie_genres_pkey PRIMARY KEY (id)