CREATE TABLE
  public.genres (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL
  );

ALTER TABLE
  public.genres
ADD
  CONSTRAINT genres_pkey PRIMARY KEY (id)