CREATE TABLE
  public.movies (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    backdrop_path text NOT NULL,
    overview text NOT NULL,
    popularity double precision NOT NULL,
    poster_path text NOT NULL,
    release_date date NOT NULL,
    duration integer NOT NULL,
    title character varying(255) NOT NULL,
    director_name character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NULL,
    deleted_at timestamp without time zone NULL
  );

ALTER TABLE
  public.movies
ADD
  CONSTRAINT movies_pkey PRIMARY KEY (id)