CREATE TABLE
  public.cinemas (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL
  );

ALTER TABLE
  public.cinemas
ADD
  CONSTRAINT cinemas_pkey PRIMARY KEY (id)