CREATE TABLE
  public.times (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "time" character varying(20) NOT NULL
  );

ALTER TABLE
  public.times
ADD
  CONSTRAINT times_pkey PRIMARY KEY (id)