CREATE TABLE
  public.payment_methods (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL
  );

ALTER TABLE
  public.payment_methods
ADD
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id)