CREATE TABLE
  public.orders (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    qr_code text NOT NULL,
    users_id uuid NOT NULL,
    schedules_id integer NOT NULL,
    payments_id integer NOT NULL,
    fullname character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    phone_number character varying(20) NOT NULL,
    created_at timestamp without time zone NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NULL
  );

ALTER TABLE
  public.orders
ADD
  CONSTRAINT orders_pkey PRIMARY KEY (id)