CREATE TABLE
  public.casts (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL
  );

ALTER TABLE
  public.casts
ADD
  CONSTRAINT casts_pkey PRIMARY KEY (id)