FROM golang:1.25-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o be-tickitz ./cmd/main.go

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /build/be-tickitz ./be-tickitz

RUN chmod +x be-tickitz

EXPOSE 8080

CMD ["./be-tickitz"]

