name: Building image backend-tickitz-go and pushing to GHCR

on: [push]

jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # - name: Login to GitHub Container Registry
      #   run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Docker image (backend)
      #   run: docker build -t ghcr.io/darari17/backend:latest .

      # - name: Push Docker image (backend)
      #   run: docker push ghcr.io/darari17/backend:latest
